const { check } = require('express-validator');

exports.createProduct = [
    check('modelo', 'El modelo es obligatorio').not().isEmpty().isLength({ max: 25 }),
    check('tipo', 'El tipo es obligatorio').not().isEmpty(),
    check('marca', 'La La marca es obligatoria').not().isEmpty().isLength({ max: 25 }),
    check('año', 'El año es obligatorio').not().isEmpty().isNumeric(),
    check('combustible', 'El combustible es obligatorio').not().isEmpty(),
    check('version', 'La version es obligatoria').not().isEmpty(),
    check('kilometraje', 'El kilometraje es obligatorio').not().isEmpty().isNumeric(),
    check('potencia', 'La potencia es obligatoria').not().isEmpty().isNumeric(),
    check('transmicion', 'La transmicion es obligatoria').not().isEmpty(),
    check('puertas', 'Las puertas son obligatorias').not().isEmpty().isNumeric(),
    check('traccion', 'La traccion es obligatoria').not().isEmpty(),
    check('motor', 'El motor es obligatorio').not().isEmpty(),
    check('tanque', 'El tanque es obligatorio').not().isEmpty().isNumeric(),
    check('direccion', 'La direccion es obligatoria').not().isEmpty(),
    check('permuta', 'La permuta es obligatoria').not().isEmpty(),
    check('financiacion', 'La financiacion es obligatoria').not().isEmpty(),
    check('precio', 'El precio es obligatorio').not().isEmpty().isFloat({ min: 0 }),
    check('patente', 'La patente es obligatoria').not().isEmpty(),
    check('img', 'La imagen es obligatoria').not().isEmpty(),
];

exports.updateProduct = [
    check('modelo', 'El modelo es obligatorio').not().isEmpty().isLength({ max: 25 }),
    check('tipo', 'El tipo es obligatorio').not().isEmpty(),
    check('marca', 'La La marca es obligatoria').not().isEmpty().isLength({ max: 25 }),
    check('año', 'El año es obligatorio').not().isEmpty().isNumeric(),
    check('combustible', 'El combustible es obligatorio').not().isEmpty(),
    check('version', 'La version es obligatoria').not().isEmpty(),
    check('kilometraje', 'El kilometraje es obligatorio').not().isEmpty().isNumeric(),
    check('potencia', 'La potencia es obligatoria').not().isEmpty().isNumeric(),
    check('transmicion', 'La transmicion es obligatoria').not().isEmpty(),
    check('puertas', 'Las puertas son obligatorias').not().isEmpty().isNumeric(),
    check('traccion', 'La traccion es obligatoria').not().isEmpty(),
    check('motor', 'El motor es obligatorio').not().isEmpty(),
    check('tanque', 'El tanque es obligatorio').not().isEmpty().isNumeric(),
    check('direccion', 'La direccion es obligatoria').not().isEmpty(),
    check('permuta', 'La permuta es obligatoria').not().isEmpty(),
    check('financiacion', 'La financiacion es obligatoria').not().isEmpty(),
    check('precio', 'El precio es obligatorio').not().isEmpty().isFloat({ min: 0 }),
    check('patente', 'La patente es obligatoria').not().isEmpty(),
    check('img', 'La imagen es obligatoria').not().isEmpty(),
];
